import Head from 'next/head';

import { DefaultLayout } from '~components/layouts/DefaultLayout';
import { useGetGamesQuery } from '~store/features/cms/games';
import { TPage } from '~types/page.types';

// eslint-disable-next-line react/function-component-definition
const Home: TPage = () => {
  const { data: games, isLoading: isGamesLoading } = useGetGamesQuery({ page: 1 });

  return (
    <>
      <Head>
        <title>Lobby - Green Jade</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul>
        {isGamesLoading && <div>Loading...</div>}
        <li>{games && games?.meta?.pagination?.total} Results</li>
        {games?.data
          && games?.data?.map((game) => {
            console.log('**game', game);
            return <li key={game.id}>{game.name}</li>;
          })}
      </ul>
    </>
  );
};

Home.getLayout = function getLayout(page) {
  return <DefaultLayout>{page}</DefaultLayout>;
};

export default Home;
