import type { NextPage } from 'next';
import Head from 'next/head';

import { Button } from '~components/atoms/Button';
import { Card } from '~components/molecules/Card';
import { useGetGamesQuery } from '~store/features/cms/games';

// eslint-disable-next-line react/function-component-definition
const Home: NextPage = () => {
  const {
    data: games,
    isLoading: isGamesLoading,
  } = useGetGamesQuery({ page: 1 });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Button variant="primary" size="xl" onClick={() => alert('Clicked')}>Play Now</Button>
        <Button variant="primary" size="lg" onClick={() => alert('Clicked')}>Play Now</Button>
        <Button variant="primary" size="md" onClick={() => alert('Clicked')}>Play Now</Button>
        <Button variant="primary" size="sm" onClick={() => alert('Clicked')}>Play Now</Button>
        <Button variant="primary" size="xs" onClick={() => alert('Clicked')}>Play Now</Button>
        <Button variant="secondary">secondary button</Button>
        <Button variant="primary-outline">primary outline</Button>
        <Card>Hello card</Card>
      </div>

      <ul>
        {isGamesLoading && <div>Loading...</div>}
        <li>{games && games?.meta?.pagination?.total} Results</li>
        {games?.data
          && games?.data?.map((game) => {
            console.log('**game', game);
            return <li key={game.id}>{game.name}</li>;
          })}
      </ul>
    </div>
  );
};

export default Home;
